// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xecho.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEcho_CfgInitialize(XEcho *InstancePtr, XEcho_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Ctrl_bus_BaseAddress = ConfigPtr->Ctrl_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEcho_Set_delay(XEcho *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEcho_WriteReg(InstancePtr->Ctrl_bus_BaseAddress, XECHO_CTRL_BUS_ADDR_DELAY_DATA, Data);
}

u32 XEcho_Get_delay(XEcho *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEcho_ReadReg(InstancePtr->Ctrl_bus_BaseAddress, XECHO_CTRL_BUS_ADDR_DELAY_DATA);
    return Data;
}

