// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xecho.h"

extern XEcho_Config XEcho_ConfigTable[];

XEcho_Config *XEcho_LookupConfig(u16 DeviceId) {
	XEcho_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XECHO_NUM_INSTANCES; Index++) {
		if (XEcho_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEcho_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEcho_Initialize(XEcho *InstancePtr, u16 DeviceId) {
	XEcho_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEcho_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEcho_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

